// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/chat.proto

package go_micro_srv_chat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7e7dde45555b7d, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RegisterResponse struct {
	Connected            bool     `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7e7dde45555b7d, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetConnected() bool {
	if m != nil {
		return m.Connected
	}
	return false
}

type UnregisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterRequest) Reset()         { *m = UnregisterRequest{} }
func (m *UnregisterRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterRequest) ProtoMessage()    {}
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7e7dde45555b7d, []int{2}
}

func (m *UnregisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterRequest.Unmarshal(m, b)
}
func (m *UnregisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterRequest.Merge(m, src)
}
func (m *UnregisterRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterRequest.Size(m)
}
func (m *UnregisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterRequest proto.InternalMessageInfo

func (m *UnregisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UnregisterResponse struct {
	Connected            bool     `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterResponse) Reset()         { *m = UnregisterResponse{} }
func (m *UnregisterResponse) String() string { return proto.CompactTextString(m) }
func (*UnregisterResponse) ProtoMessage()    {}
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7e7dde45555b7d, []int{3}
}

func (m *UnregisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterResponse.Unmarshal(m, b)
}
func (m *UnregisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterResponse.Marshal(b, m, deterministic)
}
func (m *UnregisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterResponse.Merge(m, src)
}
func (m *UnregisterResponse) XXX_Size() int {
	return xxx_messageInfo_UnregisterResponse.Size(m)
}
func (m *UnregisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterResponse proto.InternalMessageInfo

func (m *UnregisterResponse) GetConnected() bool {
	if m != nil {
		return m.Connected
	}
	return false
}

type Message struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver             string   `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7e7dde45555b7d, []int{4}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Message) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Message) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Message) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.srv.chat.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "go.micro.srv.chat.RegisterResponse")
	proto.RegisterType((*UnregisterRequest)(nil), "go.micro.srv.chat.UnregisterRequest")
	proto.RegisterType((*UnregisterResponse)(nil), "go.micro.srv.chat.UnregisterResponse")
	proto.RegisterType((*Message)(nil), "go.micro.srv.chat.Message")
}

func init() { proto.RegisterFile("proto/chat.proto", fileDescriptor_ed7e7dde45555b7d) }

var fileDescriptor_ed7e7dde45555b7d = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xa5, 0x05, 0x11, 0xc6, 0x44, 0x61, 0x0e, 0xa6, 0x69, 0x3c, 0x90, 0x55, 0x13, 0x4e, 0x85,
	0xe0, 0x27, 0x98, 0x78, 0xf3, 0x52, 0xc2, 0xc1, 0x78, 0xaa, 0xdb, 0x49, 0xd9, 0x18, 0x76, 0xeb,
	0xce, 0x82, 0xf1, 0x13, 0xfc, 0x6b, 0xd3, 0xd2, 0x52, 0x23, 0x04, 0xb9, 0xcd, 0x9b, 0x37, 0xf3,
	0x66, 0xdf, 0xcc, 0xc2, 0x20, 0xb7, 0xc6, 0x99, 0x89, 0x5c, 0x26, 0x2e, 0x2a, 0x43, 0x1c, 0x66,
	0x26, 0x5a, 0x29, 0x69, 0x4d, 0xc4, 0x76, 0x13, 0x15, 0x84, 0x78, 0x81, 0xab, 0x98, 0x32, 0xc5,
	0x8e, 0x6c, 0x4c, 0x1f, 0x6b, 0x62, 0x87, 0x21, 0xf4, 0xd6, 0x4c, 0x56, 0x27, 0x2b, 0x0a, 0xbc,
	0x91, 0x37, 0xee, 0xc7, 0x3b, 0x5c, 0x70, 0x79, 0xc2, 0xfc, 0x69, 0x6c, 0x1a, 0xf8, 0x5b, 0xae,
	0xc6, 0x78, 0x09, 0xbe, 0x4a, 0x83, 0x76, 0x99, 0xf5, 0x55, 0x2a, 0xa6, 0x30, 0x68, 0xa4, 0x39,
	0x37, 0x9a, 0x09, 0x6f, 0xa0, 0x2f, 0x8d, 0xd6, 0x24, 0x1d, 0xa5, 0xa5, 0x78, 0x2f, 0x6e, 0x12,
	0x62, 0x02, 0xc3, 0x85, 0xb6, 0xa7, 0x3f, 0x47, 0xcc, 0x00, 0x7f, 0x37, 0x9c, 0x34, 0x44, 0xc2,
	0xf9, 0x33, 0x31, 0x27, 0x19, 0xe1, 0x35, 0x74, 0x99, 0x74, 0x4a, 0xb6, 0x12, 0xae, 0x50, 0x31,
	0xd2, 0x92, 0x24, 0xb5, 0x21, 0x5b, 0xbb, 0xac, 0x31, 0x0e, 0xa0, 0xbd, 0xe2, 0xac, 0xb2, 0x59,
	0x84, 0x88, 0xd0, 0x71, 0x5f, 0x39, 0x05, 0x9d, 0x91, 0x37, 0x3e, 0x8b, 0xcb, 0x78, 0xf6, 0xed,
	0xc3, 0xc5, 0xe3, 0x32, 0x71, 0x73, 0xb2, 0x1b, 0x25, 0x09, 0x17, 0xd0, 0xab, 0x77, 0x81, 0x22,
	0xda, 0x3b, 0x43, 0xf4, 0xe7, 0x06, 0xe1, 0xed, 0xd1, 0x9a, 0xad, 0x4f, 0xd1, 0xc2, 0x57, 0x80,
	0xc6, 0x3f, 0xde, 0x1d, 0x68, 0xda, 0xdb, 0x67, 0x78, 0xff, 0x4f, 0xd5, 0x4e, 0xfc, 0x09, 0xba,
	0x73, 0x23, 0xdf, 0xc9, 0x61, 0x78, 0xa0, 0xa5, 0xda, 0x61, 0x78, 0x84, 0x13, 0xad, 0xb1, 0x37,
	0xf5, 0xde, 0xba, 0xe5, 0xe7, 0x7b, 0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x56, 0x98, 0xf0,
	0x90, 0x02, 0x00, 0x00,
}
